name: 'tiki_airflow'
version: '1.0.0'
config-version: 2

profile: 'tiki_airflow'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tiki_airflow:
    +materialized: incremental